### PR TITLE
fix: Remove top level dependencies

### PR DESCRIPTION
**Pull request by janpio**

### CODE REVIEW

**Comment by millsp** [comment]
Once https://github.com/prisma/prisma/pull/7834 is merged, well need to re-adapt `core-features/client-install-on-generate` to have a parent folder with `node_modules` with `prisma` & `@prisma/client` installed and a sub folder with `node_modules` and no `@prisma/client` (the actual test). This way we can keep things the same testing logic after merging *this* PR.

**Review by millsp — APPROVED** [review]

**Comment by janpio** [comment]
> well need to re-adapt `core-features/client-install-on-generate` to have a parent folder with `node_modules` with `prisma` & `@prisma/client` installed and a sub folder with `node_modules` and no `@prisma/client` (the actual test).

Why though? This test fundamentally should just make sure that the Client is installed during `generate` when it is missing. Wouldn't that adapted test test a special case of that?

**Comment by janpio** [comment]
That totally did not work, the next commit already created the dependency again :( 
https://github.com/prisma/e2e-tests/commit/4bc1ee99e549c1f60485328f8bc20be0e73f0cb8
Must have missed something.

(Or one of the scripts was still running... will try to kill them and delete deps again)

**Comment by janpio** [comment]
Seems it was the already running script - now it seems fine and persist.

**Pull request merged**
