### PR TITLE
fix(studio): tests

### PR DESCRIPTION
**Pull request by sdnts**
Fixed a serialization issue in Studio that prompted this

### CODE REVIEW

**Review by millsp — APPROVED** [review]

**Comment by millsp** [comment]
@madebysid Test is failing. Should we wait for a `studio` update?

**Comment by sdnts** [comment]
I thought this _was_ the upgrade. Let me double check

**Comment by sdnts** [comment]
Tests seem to be passing locally now after I merged in `dev`, so let's see what happens

**Review by Jolg42 — APPROVED** [review]

**Comment by Jolg42** [comment]
Needed after https://github.com/prisma/prisma/pull/10780 was merged

**Pull request merged**
