### PR TITLE
refactor: Remove all dotenv packages.

### LINKED ISSUE #1792: Remove dotenv
Some project still use `dotenv` locally in the script, that should not be neccesary any more. 
We should just be able to remove all the `package.json` entries and their uses in the project files:

https://github.com/prisma/e2e-tests/search?q=dotenv

### PR DESCRIPTION
**Pull request by ShubhankarKG**
1. Removes all dotenv instances.
2. Regenerate yarn.lock files for corresponding changes

closes #1792

### CODE REVIEW

**Comment by millsp** [comment]
Thanks @ShubhankarKG!

**Comment by ShubhankarKG** [comment]
Hey! Any updates on this ?

**Review by aqrln — APPROVED** [review]

**Comment by janpio** [comment]
For some reason CI does not seem to start here :/ I think we should be fine merging without.

**Comment by ShubhankarKG** [comment]
Thanks!

**Pull request merged**
