### PR TITLE
fix(driver-adapters): pg import

### PR DESCRIPTION
**Pull request by jkomyno**
Fix `pg` import and test failures.
See:
- [Github Actions](https://github.com/prisma/ecosystem-tests/actions/runs/8143406872/job/22255364274)
- [companion Prisma PR](https://github.com/prisma/prisma/pull/23311)

### CODE REVIEW

**Comment by janpio** [comment]
Tests are failing.

**Comment by Jolg42** [comment]
Looks like the tests are also failing on the `dev` branch, see https://github.com/prisma/ecosystem-tests/actions/runs/8153844907

Someone needs to investigate.

**Comment by janpio** [comment]
I have to assume that is what @jkomyno tried to do here, but as there is no linked issue that describes that and just a request for review from me I am not sure.

**Comment by apolanc** [comment]
What's this about?

**Comment by jkomyno** [comment]
Closing this, as it was a leftover from https://prisma-company.slack.com/archives/C058VM009HT/p1709641665107019.

**Pull request closed without merging**
