### PR TITLE
feat: add Debian latest arm OS support

### PR DESCRIPTION
**Pull request by jkomyno**
New OS support:
- [x] `debian-latest-arm-openssl-1.1.x`

The additional tests were prompted by [this user comment](https://github.com/prisma/prisma/issues/16182#issuecomment-1382875194).

Notes:
- ~~This PR will fail until https://github.com/prisma/prisma/pull/17322 is merged~~
- ~~This PR will fail until https://github.com/prisma/ecosystem-tests/pull/3373 is merged~~

### CODE REVIEW

**Comment by Jolg42** [comment]
@jkomyno  Currently fails with
https://github.com/prisma/ecosystem-tests/actions/runs/3929447062/jobs/6718276315#step:9:1049
```
ERROR: failed to solve: process "/bin/sh -c ./version.sh" did not complete successfully: exit code: 1
```

**Comment by jkomyno** [comment]
@Jolg42 yes, that reproduces this issue: https://github.com/prisma/prisma/issues/17284

I have yet to investigate, but it looks like we don't store `linux-arm-openssl-1.1.x` images on `binaries.prisma.sh`

**Comment by Jolg42** [comment]
@jkomyno  This is expected I think

See https://github.com/prisma/prisma/issues/5379
https://github.com/prisma/prisma/issues/5497

We actually shipped support in https://github.com/prisma/prisma/releases/tag/2.14.0
But only for Linux ARM64 support and our binaryTarget name was `"linux-arm-openssl-1.1.x"` I think we fixed that later and renamed it to `"linux-arm64-openssl-1.1.x"`

But that means "linux-arm-openssl-1.1.x" is not a thing, it's reserved for 32bit I guess now

**Comment by Jolg42** [comment]
The PR where we renamed `"linux-arm-openssl-1.1.x"` to `"linux-arm64-openssl-1.1.x"`
https://github.com/prisma/engines-wrapper/pull/173

**Comment by Jolg42** [comment]
Weird how tests results are not showing...!

**Comment by Jolg42** [comment]
Not sure why these "unrelated" tests are failing for this [commit](https://github.com/prisma/ecosystem-tests/pull/3375/commits/7c22575ae4bfd6abc11babe585a85ff6db1ddec3) 
Screenshot 2023-01-16 at 18 30 53

It looks like the merge main triggered the CI

**Review by Jolg42 — APPROVED** [review]
Looks good! 
Note: check if docker tests are passing before merging

**Comment by jkomyno** [comment]
Only two "optional tests" are failing, merging this.

**Pull request merged**
