### PR TITLE
fix: New planetscale initialization

### PR DESCRIPTION
**Pull request by SevInf**
See prisma/prisma#21883

### CODE REVIEW

**Comment by janpio** [comment]
Is it expected that this works right now?
Maybe because our tests are JS?

**Comment by Jolg42** [comment]
Sounds like JS to me indeed.

Let's keep this PR open? I'm curious to see tests failing once we merge https://github.com/prisma/prisma/pull/21883 and then this PR should fix them.

**Review by Jolg42 — APPROVED** [review]

**Comment by SevInf** [comment]
>Is it expected that this works right now?
>Maybe because our tests are JS?

Yes, programmatic interface of `Client` and `Connection` is almost identical, so without TS it just works.

**Comment by Jolg42** [comment]
@SevInf It's actually not failing, see logs https://github.com/prisma/ecosystem-tests/actions/runs/6826041185/job/18565227620


Note:  `5.6.0-dev.86` was released by
https://github.com/prisma/prisma/actions/runs/6825701068
on your commit
https://github.com/prisma/prisma/commit/f9db477a8680fc1f3bc2c93dd5f5e3eee34fe5b8

**Comment by SevInf** [comment]
Turns out, driver-adapters don't update automatically, in current dev it is still at [5.5.2](https://github.com/prisma/ecosystem-tests/blob/e38a5b942ccaf03666ef29fef4100ad9b210b587/driver-adapters/planetscale-node-basic/package.json#L15).

If I update it manually, I get a failure as expected:

```
 FAIL  ./index.test.js
  ● Test suite failed to run

    TypeError: PrismaPlanetScale must be initialized with an instance of Client:
    import { Client } from '@planetscale/database'
    const client = new Client({ url })
    const adapter = new PrismaPlanetScale(client)
```

**Comment by Jolg42** [comment]
Update happened!

**Comment by Jolg42** [comment]
Now failing as expected on main https://github.com/prisma/ecosystem-tests/actions/runs/6853648850/job/18635007879#step:8:214
```
FAIL ./index.test.js
  ● Test suite failed to run

    TypeError: PrismaPlanetScale must be initialized with an instance of Client:
    import { Client } from '@planetscale/database'
    const client = new Client({ url })
    const adapter = new PrismaPlanetScale(client)

       7 |
       8 | const connection = connect({ url: connectionString })
    >  9 | const adapter = new PrismaPlanetScale(connection)
         |                 ^
      10 | const prisma = new PrismaClient({ adapter })
      11 |
      12 | exports.handler = async () => {

      at new PrismaPlanetScale (node_modules/.pnpm/@prisma+adapter-planetscale@5.6.0-dev.98_@planetscale+database@1.11.0/node_modules/@prisma/adapter-planetscale/dist/index.js:218:13)
      at Object.<anonymous> (index.js:9:17)
      at Object.require (index.test.js:3:21)
```

**Comment by Jolg42** [comment]
@SevInf There is something weird with the lambda test, still failing in this PR
https://github.com/prisma/ecosystem-tests/blob/fix/planetscale-init/driver-adapters/planetscale-lambda-basic/index.test.js

https://github.com/prisma/ecosystem-tests/actions/runs/6853805528/job/18635586688?pr=4226#step:8:308
```
> planetscale-lambda-basic@0.1.0 test /home/runner/work/ecosystem-tests/ecosystem-tests/driver-adapters/planetscale-lambda-basic
> jest index.test.js

  console.log
    new TextDecoder().decode(response.Payload) {"errorType":"TypeError","errorMessage":"PrismaPlanetScale must be initialized with an instance of Client:\nimport { Client } from '@planetscale/database'\nconst client = new Client({ url })\nconst adapter = new PrismaPlanetScale(client)\n","trace":["TypeError: PrismaPlanetScale must be initialized with an instance of Client:","import { Client } from '@planetscale/database'","const client = new Client({ url })","const adapter = new PrismaPlanetScale(client)","","    at new PrismaPlanetScale2 (/var/task/index.js:7814:17)","    at Object.<anonymous> (/var/task/index.js:7855:15)","    at Module._compile (node:internal/modules/cjs/loader:1256:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)","    at Module.load (node:internal/modules/cjs/loader:1119:32)","    at Module._load (node:internal/modules/cjs/loader:960:12)","    at Module.require (node:internal/modules/cjs/loader:1143:19)","    at require (node:internal/modules/cjs/helpers:119:18)","    at _tryRequireFile (file:///var/runtime/index.mjs:1002:37)","    at _tryRequire (file:///var/runtime/index.mjs:1052:25)"]}

      at Object.log (index.test.js:25:13)
```

**Comment by Jolg42** [comment]
And it's passing all the tests now ✅

**Pull request merged**
