### PR TITLE
fix Cloudflare Pages integration

### PR DESCRIPTION
**Pull request by petebacondarwin**
There is a bug in `wrangler pages deploy` where it will still try to compile the `functions` directory even if the `_worker.js` directory exists. The steps in this PR should work around that (and the fact that we cannot specify `--node-compat` during `wrangler pages deploy`.

### CODE REVIEW

**Comment by janpio** [comment]
Thanks!

We'll try to make this branch local so that the secrets are provided and we can try this out.

**Comment by janpio** [comment]
@petebacondarwin That partially worked: https://github.com/prisma/ecosystem-tests/pull/4575 (The remaining failure could be because we run the test twice in slightly different configurations)

**Comment by millsp** [comment]
Hey @petebacondarwin thank you so much for the PR and the workaround. We moved your commits into a mirror [PR](https://github.com/prisma/ecosystem-tests/pull/4575) to run the tests, fix our script, and apply some minor cosmetic changes. Thanks for taking the time to contribute.

**Comment by petebacondarwin** [comment]
Glad I could help.

**Pull request closed without merging**
