### PR TITLE
docs(platforms): separate serverless and other platforms

### PR DESCRIPTION
**Pull request by janpio**
Functions/Serverless vs. others.

All correct?

### CODE REVIEW

**Comment by steebchen** [comment]
I guess it depends on the definition of server less. I don't really see the need for it, but the differentiation seems logical to me.

**Review by steebchen — APPROVED** [review]

**Comment by steebchen** [comment]
(not sure why the semantic bot doesn't pick up the semantic commit change – it should)

**Review by divyenduz — APPROVED** [review]

**Comment by divyenduz** [comment]
> (not sure why the semantic bot doesn't pick up the semantic commit change – it should)

I think because the commit message doesn't have a `:`

**Comment by janpio** [comment]
> 
> 
> > (not sure why the semantic bot doesn't pick up the semantic commit change – it should)
> 
> I think because the commit message doesn't have a `:`

It _should_ be happy with either the commit message or the PR title. But will be fixed on merge.

> I guess it depends on the definition of server less. 

Can you elaborate on that? I used this in the way is usually used in the market now to mean function like, stateless code execution.

**Comment by steebchen** [comment]
> I think because the commit message doesn't have a :

Yes, but the (edited) title should have precedence. I was actually quite sure that it would.

**Comment by steebchen** [comment]
> Can you elaborate on that?

Let's not, fine by me to merge.

**Comment by janpio** [comment]
> > I think because the commit message doesn't have a :
> 
> Yes, but the (edited) title should have precedence. I was actually quite sure that it would.

Same. Seems to be a bug: https://github.com/zeke/semantic-pull-requests/issues/112#issue-686265217

**Pull request merged**
