### PR TITLE
feat(framework/sveltekit): add sveltekit

### PR DESCRIPTION
**Pull request by tnzk**
Added Svelte Kit as a framework. It works when you use `yarn dev` but breaks with `yarn preview` which serves production build. Confirmed that `./test.sh` fails on my end.

### CODE REVIEW

**Comment by tnzk** [comment]
Sorry, I forgot adding `.github/workflow`. will do later.

**Comment by tnzk** [comment]
> First-time contributors need a maintainer to approve running workflows.

@janpio seems like I'm blocked because of being too new :) could you approve it?

**Comment by janpio** [comment]
Clicki-di-click! 👍

**Comment by janpio** [comment]
And we learned something about the GH Actions setup here: The secrets are not provided by GitHub, which makes all the tests fail. 
image

**Comment by janpio** [comment]
Parellel PR where I pulled in your changes into a local branch: https://github.com/prisma/ecosystem-tests/pull/2694

**Comment by janpio** [comment]
And here it should now actually be able to run the tests https://github.com/prisma/ecosystem-tests/pull/2695

**Comment by janpio** [comment]
Seems it does not like the CI node version maybe?
```
-----------------------------
executing frameworks/sveltekit/run.sh
+ '[' -f prepare.sh ']'
+ echo ''
+ echo ''
+ echo -----------------------------
+ echo 'executing frameworks/sveltekit/run.sh'
+ set +e
+ bash run.sh
+ yarn install
yarn install v1.22.18
warning package.json: No license field
warning ../../package.json: No license field
warning kit-prisma@0.0.1: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error @sveltejs/kit@1.0.0-next.318: The engine "node" is incompatible with this module. Expected version ">=14.13". Got "12.22.12"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
+ code=1
+ set -e
+ '[' 1 -eq 0 ']'
+ '[' 1 -eq 0 ']'
+ '[' -f finally.sh ']'
+ echo 'frameworks/sveltekit done'
```

Update: Let'see https://github.com/prisma/ecosystem-tests/pull/2695/commits/30b330343c4488ecd05d0bfb3484b15e81504092

**Comment by tnzk** [comment]
thanks! indeed it wouldn't work on Node 12

**Comment by janpio** [comment]
Discussion about next steps here: https://github.com/prisma/ecosystem-tests/pull/2695#issuecomment-1106593040

**Comment by janpio** [comment]
Merged as https://github.com/prisma/ecosystem-tests/pull/2695

**Pull request closed without merging**
