### PR TITLE
test(core-features): Add a test for Studio

### LINKED ISSUE #1622: Add test for Prisma Studio
Context

We had to release a patch because Studio was broken after being published, tests were green in prisma/prisma and e2e

https://github.com/prisma/prisma/releases/tag/2.21.1
https://github.com/prisma/studio/issues/659

So it seems that adding a test here to check if Studio work would bring more confidence in our automated testing. Maybe @madebysid has an idea about what we can test here exactly.

### PR DESCRIPTION
**Pull request by sdnts**
Closes #1622

### CODE REVIEW

**Comment by sdnts** [comment]
I noticed I had to create a `test.sh` file. Is the README out of date? I can update it if so.

**Comment by Jolg42** [comment]
Thanks @madebysid looks good!

**Review by janpio — APPROVED** [review]
Test looks great, a README would be nice.

**Comment by Jolg42** [comment]
> I noticed I had to create a `test.sh` file. Is the README out of date? I can update it if so.

Do you mean the main README that says to have `run.sh`?

**Comment by sdnts** [comment]
@Jolg42 Yeah, the main README asked me to put everything in `run.sh`, but as I understand it, `run.sh` sets thing up, and `tests.sh` runs tests

@janpio I'll add a README to the studio project

**Comment by janpio** [comment]
> I noticed I had to create a `test.sh` file. Is the README out of date? I can update it if so.

Very possible, best check the script that runs the tests (search for `run.sh` and `test.sh` in the codebase to find).

**Comment by sdnts** [comment]
Yeah looks like it: https://github.com/prisma/e2e-tests/blob/dev/.github/scripts/test-project.sh#L50

I updated the main README.

It retries `test.sh` too, so it's probably a good idea to have it anyway.

**Comment by janpio** [comment]
I think how you split it between run and test makes sense.

**Pull request merged**
